### ISSUE TITLE
Error when downloading mods for Project Zomboid

### ISSUE THREAD

**Issue by HuggedJacker** [NethercraftMC5608/NetherWorkshopDownloader#11]
**Describe the bug**
I can't download anything from NWD legacy

**To Reproduce**
1. Open NWD Legacy
2. Enter Any Workshop ID.
3. Click on download and select the path.
4. See error in the cmd window.

**Expected behavior**
Mod will be downloaded.

**Screenshots**
![NetherWorkshopDownloader2_4chSnvcr3K](https://user-images.githubusercontent.com/89655926/206886739-d9409d08-8db9-47d5-8e31-3255f06ecd31.png)

https://user-images.githubusercontent.com/89655926/206886896-782b656f-f53e-45a6-b13f-e75386a4c7da.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Brave
 - Version: 22h2

**Smartphone (please complete the following information):**
 - Device: Don't have one

**Additional context**
I also tried to redownload  NWD legacy but still same error
the error log:

NetherWorkshopDownloader2 Legacy
https://github.com/NethercraftMC5608/NetherWorkshopDownloader/releases/tag/Legacy

Querying API in background.
API is connected
108600
Mod
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "NetherWorkshopDownloader2.py", line 256, in downloadid
  File "NetherWorkshopDownloader2.py", line 231, in launch
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'config\\steamapps\\workshop\\content\\108600'

**Comment by HuggedJacker** [comment]
@VovoloGames I will check workshop dl out thanks for the info.
