### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 524:

### ISSUE THREAD

**Issue by plainnine** [NethercraftMC5608/NetherWorkshopDownloader#9]
Querying API in background.
API is connected 👍
xcom 2
API SUPPORT!
['255710', '268500', '265930', '431960', '32470', '220200', '262060', '1118200', '394360']
NetherWorkshopDownloader2.py:309: DeprecationWarning: URLopener style of invoking requests is deprecated. Use newer urlopen functions/methods
['1169625825'] 268500
[]
Mod
Downloading: 1169625825
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "NetherWorkshopDownloader2.py", line 377, in downloadid
  File "NetherWorkshopDownloader2.py", line 309, in launch
  File "NetherWorkshopDownloader2.py", line 265, in apidownload
  File "urllib\request.py", line 1822, in retrieve
  File "urllib\request.py", line 1788, in open
  File "urllib\request.py", line 1966, in open_http
  File "urllib\request.py", line 1960, in _open_generic_http
  File "urllib\request.py", line 1982, in http_error
  File "urllib\request.py", line 1987, in http_error_default
urllib.error.HTTPError: HTTP Error 524:

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: NetherWorkshopDownloader2 V2.1A

**Comment by NethercraftMC5608** [comment]
**Error 524 is due to a timeout, this is a steamcmd limitation when downloading 1gb+ files. 

This may be fixed in later versions.**
